# Generated by Django 5.0.6 on 2024-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_imagen_servicio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(upload_to='blog/images'),
        ),
    ]
