# Generated by Django 5.0.6 on 2024-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_servicio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='fecha',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
