# Generated by Django 5.0.6 on 2024-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_fecha_solicitud_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='tickets/images'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
